# Generated by Django 2.2 on 2022-08-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BolgPost',
            new_name='BlogPost',
        ),
    ]
